export const NOTES_LIST_REQUEST = 'NOTES_LIST_REQUEST'
export const NOTES_LIST_SUCCESS = 'NOTES_LIST_SUCCESS'
export const NOTES_LIST_ERROR = 'NOTES_LIST_ERROR'

export const NOTE_DETAIL_REQUEST = 'NOTE_DETAIL_REQUEST'
export const NOTE_DETAIL_SUCCESS = 'NOTE_DETAIL_SUCCESS'
export const NOTE_DETAIL_ERROR = 'NOTE_DETAIL_ERROR'

export const NOTE_UPDATE_REQUEST = 'NOTE_UPDATE_REQUEST'
export const NOTE_UPDATE_SUCCESS = 'NOTE_UPDATE_SUCCESS'
export const NOTE_UPDATE_ERROR = 'NOTE_UPDATE_ERROR'

export const NOTE_DELETE_REQUEST = 'NOTE_DELETE_REQUEST'
export const NOTE_DELETE_SUCCESS = 'NOTE_DELETE_SUCCESS'
export const NOTE_DELETE_ERROR = 'NOTE_DELETE_ERROR'

export const NOTE_CREATE_REQUEST = 'NOTE_CREATE_REQUEST'
export const NOTE_CREATE_SUCCESS = 'NOTE_CREATE_SUCCESS'
export const NOTE_CREATE_ERROR = 'NOTE_CREATE_ERROR'

export const RESET_FLAGS = 'RESET_FLAGS'
